export const products = [
        {
                coverImage: "./assets/img/phone-cover.jpg",
                name: 'Phone XL',
                price: 799,
                description: 'A large phone with one of the best screens',
                heading1: 'Light',
                heading2: 'Beatiful',
                heading3: 'Fast',
                headingtext1: 'text text text text text text text text text text text text text text text text ',
                headingtext2: 'text text text text text text text text text text text text text text text text ',
                headingtext3: 'text text text text text text text text text text text text text text text text ',
        },
        {
                coverImage: "./assets/img/phone-cover.jpg",
                name: 'Phone Mini',
                price: 699,
                description: 'A great phone with one of the best cameras',
                heading1: 'Light',
                heading2: 'Beatiful',
                heading3: 'Fast',
                headingtext1: 'text text text text text text text text text text text text text text text text ',
                headingtext2: 'text text text text text text text text text text text text text text text text ',
                headingtext3: 'text text text text text text text text text text text text text text text text ',
        },
        {
                coverImage: "./assets/img/phone-cover.jpg",
                name: 'Phone Standard',
                price: 299,
                description: '',
                heading1: 'Light',
                heading2: 'Beatiful',
                heading3: 'Fast',
                headingtext1: 'text text text text text text text text text text text text text text text text ',
                headingtext2: 'text text text text text text text text text text text text text text text text ',
                headingtext3: 'text text text text text text text text text text text text text text text text ',
        },
        {
                "id": 1,
                "char_name": "モンキー・D・ルフィ",
                "ship_name": "サウザンド・サニー号",
                "birthday": "05-05",
                "age": 19,
                "height": 174,
                "blood type": "F型",
                "place_of_birth": "東の海  ドーン島 ゴア王国 フーシャ村",
                "favorite_food": "肉全般",
                "bounty": "1,500,000,000",
                "cv": "田中真弓、高乃麗（OVA『倒せ!海賊ギャンザック』）",
                "popular_name": "麦わらのルフィ",
                "devil_fruit": "ゴムゴムの実（超人系）",
                "sovereign_haki": "あり",
                "observation_haki": "あり",
                "armameent_haki": "あり",
                "belongings": "麦わらの一味/船長、麦わら大船団/大頭",
                "gender": "男性",
                "first_appearance_commic": "01",
                "first_appearance_story": 1,
                "first_appearance_story_title": "ROMANCE DAWNー冒険の夜明けー",
                "face_img": "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png",
                "img": "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png",
                "ship_img": "https://1.bp.blogspot.com/-7aJ-w9XA0Go/X-_FsBS3SLI/AAAAAAAA9n8/TrCdDc1A8UgLoVjXvOqyGZkLmUCTN943wCLcBGAsYHQ/w320-h297/Hello%2BAnime%2B%2521%2B%2B%2528156%2529.jpg"
        },
        {
                "id": 2,
                "char_name": "ロロノア・ゾロ",
                "ship_name": "サウザンド・サニー号",
                "birthday": "11-11",
                "age": 21,
                "height": 181,
                "blood type": "XF型",
                "place_of_birth": "東の海 シモツキ村",
                "favorite_food": "白米、海獣の肉、酒に合う物",
                "bounty": "320,000,000",
                "cv": "中井和哉、浦和めぐみ（幼少期）、高木渉（OVA『倒せ!海賊ギャンザック』）",
                "popular_name": "海賊狩りのゾロ",
                "devil_fruit": "",
                "sovereign_haki": "なし",
                "observation_haki": "あり",
                "armameent_haki": "あり",
                "belongings": "麦わらの一味/戦闘員（剣士）、麦わら大船団",
                "gender": "男性",
                "first_appearance_commic": "01",
                "first_appearance_story": 3,
                "first_appearance_story_title": "海賊狩りのゾロ登場",
                "face_img": "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png",
                "img": "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png",
                "ship_img": "https://1.bp.blogspot.com/-7aJ-w9XA0Go/X-_FsBS3SLI/AAAAAAAA9n8/TrCdDc1A8UgLoVjXvOqyGZkLmUCTN943wCLcBGAsYHQ/w320-h297/Hello%2BAnime%2B%2521%2B%2B%2528156%2529.jpg"
        },
        {
                "id": 3,
                "char_name": "ナミ",
                "ship_name": "サウザンド・サニー号",
                "birthday": "07-03",
                "age": 20,
                "height": 170,
                "blood type": "X型",
                "place_of_birth": "東の海 コノミ諸島 ココヤシ村（オイコット王国の戦災孤児）",
                "favorite_food": "みかん、フルーツ全般",
                "bounty": "66,000,000",
                "cv": "岡村明美、山崎和佳奈（代役）、豊口めぐみ（OVA『倒せ!海賊ギャンザック』）",
                "popular_name": "泥棒猫",
                "devil_fruit": "",
                "sovereign_haki": "なし",
                "observation_haki": "なし",
                "armameent_haki": "なし",
                "belongings": "麦わらの一味/航海士、麦わら大船団",
                "gender": "女性",
                "first_appearance_commic": "01",
                "first_appearance_story": 8,
                "first_appearance_story_title": "ナミ登場",
                "face_img": "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png",
                "img": "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png",
                "ship_img": "https://1.bp.blogspot.com/-7aJ-w9XA0Go/X-_FsBS3SLI/AAAAAAAA9n8/TrCdDc1A8UgLoVjXvOqyGZkLmUCTN943wCLcBGAsYHQ/w320-h297/Hello%2BAnime%2B%2521%2B%2B%2528156%2529.jpg"
        },
        {
                "id": 4,
                "char_name": "ウソップ",
                "ship_name": "サウザンド・サニー号",
                "birthday": "04-01",
                "age": 19,
                "height": 176,
                "blood type": "S型",
                "place_of_birth": "東の海 ゲッコー諸島 シロップ村",
                "favorite_food": "秋島のサンマ、旬の魚",
                "bounty": "200,000,000",
                "cv": "山口勝平",
                "popular_name": "ゴッド、狙撃の王様（そげキングとして）",
                "devil_fruit": "",
                "sovereign_haki": "なし",
                "observation_haki": "なし",
                "armameent_haki": "なし",
                "belongings": "麦わらの一味/狙撃手、麦わら大船団",
                "gender": "男性",
                "first_appearance_commic": "03",
                "first_appearance_story": 23,
                "first_appearance_story_title": "キャプテン・ウソップ登場",
                "face_img": "https://one-piece.com/assets/images/anime/character/data/usopp/face.jpg",
                "img": "https://one-piece.com/assets/images/anime/character/data/usopp/img.jpg",
                "ship_img": "https://1.bp.blogspot.com/-7aJ-w9XA0Go/X-_FsBS3SLI/AAAAAAAA9n8/TrCdDc1A8UgLoVjXvOqyGZkLmUCTN943wCLcBGAsYHQ/w320-h297/Hello%2BAnime%2B%2521%2B%2B%2528156%2529.jpg"
        }
];
